name: Run DeepSeek Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # إضافة هذه الخطوات للتحقق من الدليل
      - name: Check working directory
        run: pwd

      - name: List files in the directory
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pyyaml requests

      - name: Run DeepSeek script
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: python scripts/run_deepseek.py
